# Generated by Django 5.2.11 on 2026-03-25 00:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Title of the conversation (auto-generated or user-defined)",
                        max_length=255,
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[("text_rag", "Text Rag"), ("graph_rag", "Graph Rag")],
                        default="text_rag",
                        help_text="Type of RAG agent to use",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Whether this conversation is active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this conversation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "conversations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant"), ("system", "System")],
                        help_text="Role of the message sender",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(help_text="Content of the message")),
                (
                    "sources",
                    models.JSONField(
                        blank=True, default=list, help_text="List of source chunk IDs used for this response"
                    ),
                ),
                (
                    "retrieval_scores",
                    models.JSONField(blank=True, default=dict, help_text="Retrieval scores for each source"),
                ),
                ("token_count", models.PositiveIntegerField(default=0, help_text="Number of tokens in this message")),
                (
                    "model_used",
                    models.CharField(
                        blank=True, default="", help_text="LLM model used for generating this message", max_length=50
                    ),
                ),
                (
                    "embedding_id",
                    models.CharField(
                        blank=True, default="", help_text="ID of the message embedding in Milvus", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="Conversation this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat_agent.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["user", "-updated_at"], name="conversatio_user_id_e93dff_idx"),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["is_active"], name="conversatio_is_acti_a70b65_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["conversation", "created_at"], name="messages_convers_3ebb41_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["role"], name="messages_role_8be1df_idx"),
        ),
    ]
