# Generated by Django 5.2.11 on 2026-03-04 06:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents_parser", "0002_add_storage_backend"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineExecution",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("current_step", models.CharField(default="", max_length=50)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_duration_ms", models.PositiveBigIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("error_step", models.CharField(blank=True, default="", max_length=50)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_execution",
                        to="documents_parser.document",
                    ),
                ),
            ],
            options={
                "db_table": "pipeline_executions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PipelineStep",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("step_name", models.CharField(max_length=50)),
                ("step_order", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveBigIntegerField(default=0)),
                ("input_data", models.JSONField(blank=True, default=dict)),
                ("output_data", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="document_pipeline_manager.pipelineexecution",
                    ),
                ),
            ],
            options={
                "db_table": "pipeline_steps",
                "ordering": ["step_order"],
            },
        ),
        migrations.AddIndex(
            model_name="pipelineexecution",
            index=models.Index(fields=["status"], name="pipeline_ex_status_dc870e_idx"),
        ),
        migrations.AddIndex(
            model_name="pipelineexecution",
            index=models.Index(fields=["created_at"], name="pipeline_ex_created_da1844_idx"),
        ),
        migrations.AddIndex(
            model_name="pipelinestep",
            index=models.Index(fields=["execution", "step_order"], name="pipeline_st_executi_32dc7a_idx"),
        ),
        migrations.AddIndex(
            model_name="pipelinestep",
            index=models.Index(fields=["status"], name="pipeline_st_status_081283_idx"),
        ),
        migrations.AddConstraint(
            model_name="pipelinestep",
            constraint=models.UniqueConstraint(fields=("execution", "step_name"), name="unique_execution_step_name"),
        ),
    ]
