# Generated by Django 5.2.11 on 2026-02-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents_parser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="storage_backend",
            field=models.CharField(default="s3", max_length=20),
        ),
        migrations.AddField(
            model_name="document",
            name="storage_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
