# Generated by Django 5.2.11 on 2026-03-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents_parser", "0002_add_storage_backend"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="parsed_content",
            field=models.TextField(blank=True, default=""),
        ),
    ]
