# Generated by Django 5.2.11 on 2026-03-17 07:47

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents_parser", "0003_add_parsed_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentchunk",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(fields=["search_vector"], name="document_ch_search__bad16b_idx"),
        ),
    ]
